name: Test Add File to Git from Action
on: push
  workflow_call:
    secrets:     
      GH_TOKEN:  
        description: 'GH token with access to this repo'
        required: true
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt

      - name: setup git config
        run: |
          git config user.name "chrisvugrinec"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add time.txt
          git commit -am "new date commit"
          git push origin main
          with:
            repo-token: ${{ secrets.GH_TOKEN }}
