name: Test Add File to Git from Action
on: push
jobs:

  
  date:
    runs-on: ubuntu-latest
  
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:

      - name: say hello (testing secret)
        run: |
          echo "Hello {{ secrets.HW_DEMO }}"

      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt

      - name: setup git config
        run: |
          git config user.name "chrisvugrinec"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add time.txt
          git commit -am "new date commit"
          git push origin main
